apiVersion: v1
kind: ServiceAccount
metadata:
  name: community-api-gateway
  namespace: mana-community
  labels:
    app: community-api-gateway
  annotations:
    eks.amazonaws.com/role-arn: ${IAM_ROLE_ARN}
