apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  redis-host: {{ .Values.config.redisHost | quote }}
  redis-port: {{ .Values.config.redisPort | quote }}
  jwt-issuer-uri: {{ .Values.config.jwtIssuerUri | quote }}
  tracing-sample-rate: {{ .Values.config.tracingSampleRate | quote }}
