spring:
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URLS:http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@discovery-service-0.discovery-service-headless:8761/eureka/,http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@discovery-service-1.discovery-service-headless:8761/eureka/}
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 30000
  instance:
    hostname: ${HOSTNAME}.discovery-service-headless
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: WARN
    com.manacommunity.discovery: INFO
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    org.springframework.cloud.netflix: WARN
    org.springframework.security: WARN
