package com.manacommunity.api.security;

/**
 * Catalogue of auditable business events. Stored as {@code name()} in the
 * {@code audit_log.action} string column (not as a DB enum) so the catalogue can
 * evolve without breaking historical rows.
 */
public enum AuditAction {

    // ── User Management ──
    USER_CREATED, USER_UPDATED, USER_DELETED, ROLE_CHANGED, PERMISSION_CHANGED,

    // ── Sports ──
    PLAYER_REGISTERED, REGISTRATION_APPROVED, REGISTRATION_REJECTED,
    CAPTAIN_NOMINATED, CAPTAIN_CONFIRMED, PARTNER_CONFIRMED, PARTNER_DECLINED,
    SPORTS_EVENT_CREATED, SPORTS_EVENT_UPDATED, SPORTS_EVENT_DELETED,
    MATCH_CREATED, MATCH_UPDATED, WINNER_DECLARED, TOURNAMENT_COMPLETED,
    TOURNAMENT_SCHEDULE_SAVED, MATCH_SCHEDULED, MATCH_SCORE_UPDATED,

    // ── Auction ──
    AUCTION_STARTED, AUCTION_ENDED, BID_PLACED, PLAYER_SOLD, TEAM_CREATED,
    AUCTION_CONFIG_CREATED, AUCTION_CONFIG_UPDATED,

    // ── Marketplace ──
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    ORDER_CREATED, ORDER_UPDATED, ORDER_CANCELLED,
    DONATION_CREATED, DONATION_CLAIMED, DONATION_DELETED,
    LOST_FOUND_CREATED, LOST_FOUND_RESOLVED, LOST_FOUND_CLOSED,

    // ── Admin / Config ──
    CONFIG_UPDATED,

    // ── Pooja / Event Booking ──
    POOJA_SCHEDULE_CREATED, POOJA_SCHEDULE_UPDATED, POOJA_SCHEDULE_STATUS_CHANGED, POOJA_SCHEDULE_DELETED,
    POOJA_SLOT_RESERVED, POOJA_SLOT_RESERVATION_EXPIRED, POOJA_SLOT_RESERVATION_CANCELLED,
    POOJA_REGISTRATION_CREATED, POOJA_REGISTRATION_UPDATED, POOJA_REGISTRATION_CANCELLED,
    POOJA_REGISTRATION_DELETED,

    // ── Service Platform ──
    SERVICE_DOMAIN_CREATED, SERVICE_DOMAIN_UPDATED, SERVICE_DOMAIN_DELETED,
    SERVICE_CATEGORY_CREATED, SERVICE_CATEGORY_UPDATED, SERVICE_CATEGORY_DELETED,
    SERVICE_PROVIDER_REGISTERED, SERVICE_PROVIDER_VERIFIED, SERVICE_PROVIDER_SUSPENDED,
    SERVICE_OFFERING_CREATED, SERVICE_OFFERING_UPDATED, SERVICE_OFFERING_DELETED,
    SERVICE_REQUEST_CREATED, SERVICE_REQUEST_SUBMITTED, SERVICE_REQUEST_ASSIGNED, SERVICE_REQUEST_CANCELLED,
    SERVICE_WORK_ORDER_CREATED, SERVICE_WORK_ORDER_STATUS_UPDATED, SERVICE_WORK_ORDER_COMPLETED,

    // ── Retail ──
    RETAIL_CUSTOMER_CREATED, RETAIL_CUSTOMER_UPDATED, RETAIL_CUSTOMER_DELETED,
    RETAIL_SUPPLIER_CREATED, RETAIL_SUPPLIER_UPDATED, RETAIL_SUPPLIER_DELETED,
    RETAIL_PRODUCT_CREATED, RETAIL_PRODUCT_UPDATED, RETAIL_PRODUCT_DELETED,
    RETAIL_ORDER_CREATED, RETAIL_ORDER_UPDATED, RETAIL_ORDER_DELETED,

    // ── Privacy ──
    VIEW_PERSONAL_DATA, VIEW_CONTACT_INFO, VIEW_FAMILY_DETAILS, VIEW_DOB,
    VIEW_VISITOR_DETAILS, VIEW_VISITOR_HISTORY, VIEW_VISITOR_CONTACT,
    VIEW_PAYMENT_DATA, EXPORT_PERSONAL_DATA,
    UPDATE_PERSONAL_DATA, DELETE_PERSONAL_DATA,
    ADMIN_OVERRIDE_PII, ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_DELETION_VERIFIED, ACCOUNT_DELETION_COMPLETED, ACCESS_REVOKED
}
