apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: mana-community
  labels:
    app: config-service
    tier: infrastructure
    part-of: mana-community-os
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: config-service
