-- Add SIGNUP_SUCCESS and PASSWORD_RESET to the notification type check constraint.
-- The constraint was originally generated by Hibernate DDL and must be replaced
-- to include the two new account-lifecycle notification types.

ALTER TABLE manacommunity.notification
    DROP CONSTRAINT IF EXISTS notification_type_check;

ALTER TABLE manacommunity.notification
    ADD CONSTRAINT notification_type_check CHECK (
        type IN (
            'SCHEDULE_PUBLISHED', 'SCHEDULE_UPDATED', 'MATCH_REMINDER', 'MATCH_RESULT_POSTED',
            'REGISTRATION_RECEIVED', 'REGISTRATION_OPEN', 'REGISTRATION_CONFIRMED',
            'REGISTRATION_REJECTED', 'REGISTRATION_WITHDRAWN',
            'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_STATUS_CHANGED',
            'AUCTION_STARTED', 'AUCTION_COMPLETED', 'PLAYER_SOLD', 'BID_OUTBID',
            'TEAM_ASSIGNED', 'TEAM_CREATED', 'CAPTAIN_NOMINATED', 'CAPTAIN_CONFIRMED',
            'WINNER_NOTIFICATION', 'TOURNAMENT_COMPLETED', 'PRIZE_DISTRIBUTION',
            'TOURNAMENT_OPEN', 'TOURNAMENT_ANNOUNCEMENT',
            'GENERAL',
            'VISITOR_PENDING', 'VISITOR_CHECK_IN',
            'SIGNUP_SUCCESS', 'PASSWORD_RESET'
        )
    );


    -- V99: Safely add and backfill status column in event_pooja_sevas table.

    ALTER TABLE IF EXISTS event_pooja_sevas
        ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE';

    ALTER TABLE IF EXISTS manacommunity.event_pooja_sevas
        ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE';

    UPDATE event_pooja_sevas
        SET status = 'ACTIVE'
        WHERE status IS NULL;

    ALTER TABLE IF EXISTS event_pooja_sevas
        ALTER COLUMN status SET DEFAULT 'ACTIVE';

